export const IAM_ROUTES = {
    ROOT: "/iam",
    USERS: "/iam/users",
    USER_DETAIL: "/iam/users/:id",
    userDetail: (id: string) => `/iam/users/${id}`,
    ROLES: "/iam/roles",
    ROLE_DETAIL: "/iam/roles/:id",
    roleDetail: (id: string) => `/iam/roles/${id}`,
    POLICIES: "/iam/policies",
    POLICY_NEW: "/iam/policies/new",
    POLICY_DETAIL: "/iam/policies/:id",
    policyDetail: (id: string) => `/iam/policies/${id}`,
    GROUPS: "/iam/groups",
    GROUP_NEW: "/iam/groups/new",
    GROUP_DETAIL: "/iam/groups/:id",
    groupDetail: (id: string) => `/iam/groups/${id}`,
    // Invitations now live as a tab inside the Users page.
    INVITATIONS: "/iam/users?tab=invitations",
    // The invite form is a dialog on the Users page; invite=1 opens it on load.
    INVITATION_NEW: "/iam/users?tab=invitations&invite=1",
    ACCEPT_INVITE: "/invite/accept",
    PERMISSIONS: "/iam/permissions",
    SIMULATOR: "/iam/simulator",
    AUDIT: "/iam/audit",
    API_KEYS: "/iam/api-keys",
} as const

export const IAM_QUERY_KEYS = {
    users: ["iam", "users"] as const,
    user: (id: string) => ["iam", "users", id] as const,
    roles: ["iam", "roles"] as const,
    role: (id: string) => ["iam", "roles", id] as const,
    policies: ["iam", "policies"] as const,
    policy: (id: string) => ["iam", "policies", id] as const,
    userRoles: (userId: string) => ["iam", "user-roles", userId] as const,
    userGroups: (userId: string) => ["iam", "user-groups", userId] as const,
    userPolicies: (userId: string) => ["iam", "user-policies", userId] as const,
    rolePolicies: (roleId: string) => ["iam", "role-policies", roleId] as const,
    roleMembers: (roleId: string) => ["iam", "role-members", roleId] as const,
    groups: ["iam", "groups"] as const,
    group: (id: string) => ["iam", "groups", id] as const,
    groupMembers: (groupId: string) => ["iam", "group-members", groupId] as const,
    groupPolicies: (groupId: string) => ["iam", "group-policies", groupId] as const,
    invitations: (status?: string) => ["iam", "invitations", status ?? "all"] as const,
    auditLogs: ["iam", "audit-logs"] as const,
    accountMembers: ["iam", "account-members"] as const,
    apiKeys: ["iam", "api-keys"] as const,
    permissions: ["iam", "permissions"] as const,
}
